import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import tw, { styled } from 'twin.macro';

const Container = styled.div`
  ${tw`px-8`}
`;

const Main = styled.main`
  ${tw`min-h-screen py-16 flex flex-1 flex-col justify-center items-center`}
`;

const Title = styled.h1`
  ${tw`text-6xl my-2`}
`;

const TitleLink = styled.a`
  ${tw`text-blue-600 hover:underline focus:underline active:underline`}
`;

const Subtitle = styled.h2`
  ${tw`text-4xl my-2`}
`;

const Description = styled.p`
  ${tw`my-16 text-2xl`}
`;

const DescriptionCode = styled.code`
  ${tw`bg-gray-50 rounded p-3 text-lg font-mono`}
`;

const Grid = styled.div`
  ${tw`flex justify-center items-center flex-wrap w-full flex-col sm:(max-w-3xl flex-row)`}
`;

const Card = styled.a`
  ${tw`m-4 p-6 text-left border border-gray-200 rounded-xl transition-colors max-w-xs hover:(text-blue-600 border-blue-600) focus:(text-blue-600 border-blue-600) active:(text-blue-600 border-blue-600)`}
  h2 {
    ${tw`mb-4 text-2xl`}
  }
  p {
    ${tw`text-xl`}
  }
`;

const Footer = styled.footer`
  ${tw`flex flex-1 py-8 border-t border-gray-200 justify-center items-center`}
`;

// flex-grow should be changed to grow once twin.macro supports Tailwind v3
const FooterLink = styled.a`
  ${tw`flex flex-grow justify-center items-center`}
`;

const FooterLogo = styled.span`
  ${tw`h-4 ml-2`}
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <TitleLink href="https://nextjs.org">Next.js!</TitleLink>
        </Title>

        <Subtitle>
          (And{' '}
          <TitleLink href="https://github.com/tmwilliamlin168/nextjs-template-1">
            My Template
          </TitleLink>
          )
        </Subtitle>

        <Description>
          Get started by editing{' '}
          <DescriptionCode>pages/index.tsx</DescriptionCode>
        </Description>

        <Grid>
          <Card href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>

          <Card href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </Card>
        </Grid>
      </Main>

      <Footer>
        <FooterLink
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <FooterLogo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </FooterLogo>
        </FooterLink>
      </Footer>
    </Container>
  );
};

export default Home;
